version: '3.8'

services:
    zoo1: 
      image: confluentinc/cp-zookeeper:7.4.10
      hostname: zoo1
      container_name: zoo1
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - "2181:2181"
      extra_hosts:
        - "localhost:127.0.0.1"
      networks:
        - app-network
    
    kafka1:
      image: confluentinc/cp-kafka:7.4.10
      hostname: kafka1
      container_name: kafka1
      depends_on:
        - zoo1 
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
        KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka1:9093
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker, controller
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
        KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      networks:
        - app-network

    redis1:
      image: redis:bookworm
      hostname: redis1
      container_name: redis1
      ports: 
        - "6379:6379"
      networks:
        - app-network

    order-processor:
      build:
        context: .
        dockerfile: services/order-processor/Dockerfile
      environment:
        - KAFKA_BOOTSTRAP=kafka1:9093
        - REDIS_ADDR=redis1:6379
      depends_on:
        - kafka1
        - redis1
      networks:
        - app-network

    order-ingester:
      build:
        context: .
        dockerfile: services/order-ingester/Dockerfile
      environment:
          - KAFKA_BOOTSTRAP=kafka1:9093
      depends_on:
          - kafka1
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
